### ISSUE TITLE
Huggingface Transformer Support

### ISSUE THREAD

**Issue by YangWang92** [microsoft/VPTQ#115]
Huggingface Transformer Support

**Comment by wejoncy** [comment]
https://github.com/huggingface/transformers/pull/34770

**Comment by ForAxel** [comment]
Could you provide the compatible transformers dependency version for vptq 0.0.4? When running the code in the Python API Example, I encountered the following error, which seems to be related to the transformers version:
> AttributeError: 'LlamaConfig' object has no attribute 'quantization_config'

**Comment by ForAxel** [comment]
> Could you provide the compatible transformers dependency version for vptq 0.0.4? When running the code in the Python API Example, I encountered the following error, which seems to be related to the transformers version:
> 
> > AttributeError: 'LlamaConfig' object has no attribute 'quantization_config'

It seems that the issue was caused by my config.json not being updated to the latest version. After I installed the latest version of transformers from https://github.com/VPTQ/transformers/tree/main and synchronized the config.json with the content from Hugging Face, this problem was resolved.

**Comment by YangWang92** [comment]
Sorry, we updated our `quantization_config` field yesterday to integrate with Hugging Face https://github.com/microsoft/VPTQ/commit/139a38038ae44177cbeb92ef5110475c7541e002 and https://github.com/huggingface/transformers/pull/34770. You'll need to reinstall the latest version of VPTQ (pip install vptq -U or compile the latest main branch). Please also ensure that your model's configuration is up to date (e.g., https://huggingface.co/VPTQ-community/Meta-Llama-3.1-8B-Instruct-v12-k65536-4096-woft/commits/main/config.json), If you don't want to redownload the model, you can simply replace the Hugging Face config.json.

**Comment by YangWang92** [comment]
Supported by @wejoncy, thanks for his contribution!

https://github.com/huggingface/transformers/commit/4e27a4009d3f9d4e44e9be742e8cd742daf074f4
