### ISSUE TITLE
Question about result reproduction

### ISSUE THREAD

**Issue by ShawnzzWu** [microsoft/VPTQ#133]
![Image](https://github.com/user-attachments/assets/68a478b6-e9c4-433d-89ea-3a08c8cbefdd)

I tried this config to quantize the model but didn't get as good result as AC & AE in table 6 LLaMA-3 8B 2.24 bit. I want to ask should I compare the result with this record and whether the norm is implemented to produced this result?
Looking forward to your reply.

**Comment by YangWang92** [comment]
The llama 3-8b models in the paper have been fine-tuned, especially around ~2-bit, where even just a few hundred iterations of end-to-end fine-tuning significantly improved model accuracy. We plan to release the fine-tuning code based on llamafactory in the future, but I’m currently quite busy—please stay tuned.
