### ISSUE TITLE
Detailed code of the implementation of ops.gemm && ops.dequant

### ISSUE THREAD

**Issue by xzjwillbethin** [microsoft/VPTQ#134]
In vqliner.py,where can I see the detailed code of the implementationof ops.dequant(line 402) and ops.gemm(line:322) functions?Thanks and look forward to your answer.

**Comment by YangWang92** [comment]
https://github.com/microsoft/VPTQ/tree/main/csrc

Thanks!

**Comment by xzjwillbethin** [comment]
If I have two rounds of residual res_centroids, how do I calculate this gemm?
