### ISSUE TITLE
Colab demo: AttributeError: 'Qwen2Config' object has no attribute 'quant_config'

### ISSUE THREAD

**Issue by ch1y0q** [microsoft/VPTQ#137]
When running colab demo on https://colab.research.google.com/github/microsoft/VPTQ/blob/main/notebooks/vptq_example.ipynb , I encountered `AttributeError: 'Qwen2Config' object has no attribute 'quant_config'` when executing `m = vptq.AutoModelForCausalLM.from_pretrained("VPTQ-community/Qwen2.5-7B-Instruct-v8-k65536-0-woft", device_map='auto', dtype=torch.half)`.

![Image](https://github.com/user-attachments/assets/34b95e49-f568-4337-836c-96b7d303a9d1)

**Comment by YangWang92** [comment]
As we have updated quant_config in config.json, and you may need to update `config.json` file or VPTQ installation. Thanks for point this out, and let me update ipynb.

```bash
pip install vptq -U
```

**Comment by YangWang92** [comment]
fixed in https://github.com/microsoft/VPTQ/pull/138

Thanks!
