### ISSUE TITLE
Potential BUG in pack.py?

### ISSUE THREAD

**Issue by ForAxel** [microsoft/VPTQ#148]
I encountered an `AssertionError` while using the code in the algorithm branch to quantize the LLaMA3.1-8B model with the setting `num_res_centroids > num_centroids`. I believe that setting `num_res_centroids > num_centroids` is a valid configuration. It seems that this issue might be related to **line 128 in `pack.py`**. Specifically, I propose the following change:
```python
#res_indices = ((unpack_indice >> index_bits) & ((1 << index_bits) - 1)).view(torch.uint64).to(torch.int64)
res_indices = ((unpack_indice >> index_bits) & ((1 << res_bits) - 1)).view(torch.uint64).to(torch.int64)
```
Could you please review this part of the code and confirm if this modification is appropriate?

**Comment by YangWang92** [comment]
Let me check, thanks for your feedback!

**Comment by YangWang92** [comment]
I think it is a bug, and can you help me to pull a request to fix it. You can be a contributor of the project. Thanks!

**Comment by YangWang92** [comment]
merged! Thanks for your contribution!
