### ISSUE TITLE
Release date for quantization code?

### ISSUE THREAD

**Issue by cakeng** [microsoft/VPTQ#29]
Hello! Thank you for sharing your work! 

I have tested your quantized models on our machines, and the results are very impressive.

I wish to learn more about the VPTQ quantization process and use VPTQ in my projects for quantization.

When will the quantization code be released? Is there any estimate on the date? 

Also, when you do, could you please share the Hessians that you used for your quantization?

Thank you!

```[tasklist]
### Tasks
```

**Comment by YangWang92** [comment]
Hi @cakeng ,

Thank you for your interest in our project. I am currently preparing to organize the quantization code for VPTQ, and I expect to complete this within the next 1-2 weeks (before October 15th). 

If you urgently need it, please feel free to email me directly. The current code and environment dependencies are a bit messy, as I am still separating code that is unrelated to the content we have released so far. 

Additionally, we hope the open-source community will provide the collected Hessians. Please stay tuned, as Hessians are usually very large.

Thanks!
Yang

**Comment by YangWang92** [comment]
Hi @cakeng,
Additionally, our current inference kernel is quite basic, and the inference system relies solely on Torch itself, without optimizations for other details (especially about KV cache memory optimization and multi-GPU parallelism). 

Do you have any suggestions for further optimization of our inference processes?

Thanks!
Yang

**Comment by cakeng** [comment]
Hello @YangWang92,
Thank you for the update!

I am indeed researching a hardware-efficient inference solution for VQ-based compression methods and I would love to learn more about the VPTQ compression algorithm as soon as possible.

I will send you an email with more details!

Thank you!
Jongseok

**Comment by YangWang92** [comment]
Hi all,
I have responded to Cakeng's email. If any of you are interested in VQ's inference optimization and other expansions, please feel free to raise an issue or DM me.

Thanks!
Yang

**Comment by YangWang92** [comment]
Hi @cakeng,
I have updated the paper in the repo, and fixed some typos in the algorithm and add more inference results.

Thanks!
Yang

**Comment by dillfrescott** [comment]
Looking forward to the quantization code. Does the quantization from the original model to VPTQ require a ton of resources and time?

**Comment by YangWang92** [comment]
Hi @dillfrescott,
I am currently preparing the code, so please stay tuned. 
Additionally, VPTQ takes longer to run than GPTQ because we need time to prepare the Hessian offline and to initialize centroids using k-means. Compared to methods that require finetuning, VPTQ indeed requires less time. 

For a 7B model, VPTQ takes about 20 minutes (@8 GPUs), which is equivalent to 160 minutes @ 1 GPU (our current implementation is fully parallel, with each layer able to run on a separate GPU).

Thanks!
Yang

**Comment by dillfrescott** [comment]
@YangWang92 thank you for the info!

**Comment by rkinas** [comment]
Waiting for quantiazation code too.

**Comment by laomao0** [comment]
Looking forward to the quantization code.

**Comment by YangWang92** [comment]
Please hold on, I've been very busy. I will release an early version around this weekend on a separate branch. I will inform you all immediately after the release.

**Comment by YangWang92** [comment]
Hi @cakeng @laomao0 @dillfrescott @rkinas,

The VPTQ algorithm has been early-released at the [algorithm branch](https://github.com/microsoft/VPTQ/tree/algorithm), and you can check out the [tutorial](https://github.com/microsoft/VPTQ/blob/algorithm/algorithm.md). The current release is still in its early stages. This code is an early-release version extracted from a complete experimental codebase. Some details still need to be fully revised, so please use and test it cautiously.

Thanks!

**Comment by dillfrescott** [comment]
Awesome!!!
