### ISSUE TITLE
(Eventually) submit to exllama?

### ISSUE THREAD

**Issue by Downtown-Case** [microsoft/VPTQ#41]
The readme mentions:

>  Submit the VPTQ method to various inference frameworks (e.g., vLLM, llama.cpp).

Is there room to (eventually) integrate VPTQ into exllama as well? Exllama is currently among the most memory efficient LLM backends, and undoubtedly the most efficient at high context, but would greatly benefit from supporting this quantization method. 

https://github.com/turboderp/exllamav2

Paging @turboderp as well.
```[tasklist]
### Tasks
```

**Comment by YangWang92** [comment]
Hi @Downtown-Case, and @turboderp,

Thanks for your recommendation. We will try updating to exllamav2. I will immediately update our future plan to include exllamav2. 

VPTQ currently urgently needs to enhance inference speed; our current implementation is a naive version in PyTorch, and it requires various optimizations moving forward. 

We hope that we can join the open-source community in making VPTQ even better.

Thanks!
Yang

**Comment by Downtown-Case** [comment]
Thanks.

I wonder if there's some kind of synergy to be had? I figure you need to write kernels for the dequantization code, but exllama is pytorch, and already has optimized CUDA for most everything else. Maybe that could help you make a fast "reference" implementation?

I'm just spitballing though. I appreciate y'all adding exllama to the roadmap.

**Comment by YangWang92** [comment]
Hi @Downtown-Case,
Thank you for your quick response. 

We have a reference Pytorch implementation here (https://github.com/microsoft/VPTQ/blob/main/vptq/layers/vqlinear.py#L649-L651), where you can comment out fast_quant (our CUDA implementation) to run dequant() (https://github.com/microsoft/VPTQ/blob/main/vptq/layers/vqlinear.py#L501). 
The current naive Pytorch dequant() requires some reshaping, permuting, and gathering, so the performance in naive Torch is not ideal and is only for reference and correctness verification. 

The CUDA version of the dequant kernel is here: https://github.com/microsoft/VPTQ/blob/main/csrc/dequant_impl_packed.cu. 

What would us need to be done to integrate it into exllama?  Feel free to give us suggestions; we greatly appreciate it!
Yang
