### ISSUE TITLE
cc1plus: out of memory 

### ISSUE THREAD

**Issue by DietmarGrabowski** [microsoft/VPTQ#52]
With the latest change:
Build on WSL2, Ubuntu
export TORCH_CUDA_ARCH_LIST=8.6
pip install git+https://github.com/microsoft/VPTQ.git --no-build-isolation
......
detected during:
                  instantiation of "T cuda::ConvertFromFloat(float, T) [with T=__half]" at line 172 of /tmp/pip-req-build-8q0d34gg/csrc/dequant_impl_packed.cu
                  instantiation of "void WqA16WithOutliers_PackIndice<scalar_t,IDXBITS,ResidualBits,GROUPSIZE,OL_GroupSize,Do_Reduce>(scalar_t *, const scalar_t *, const int32_t *, const uint16_t *, const scalar_t *, const scalar_t *, const scalar_t *, const uint16_t *, const scalar_t *, const scalar_t *, const scalar_t *, int, int, int, int, int, int, int) [with scalar_t=__half, IDXBITS=16, ResidualBits=16, GROUPSIZE=16, OL_GroupSize=4, Do_Reduce=4]" at line 617 of /tmp/pip-req-build-8q0d34gg/csrc/dequant_impl_packed.cu

 cc1plus: out of memory allocating 18446744058020852416 bytes after a total of 254558208 bytes
      ninja: build stopped: subcommand failed.
      Traceback (most recent call last):
        File "/root/miniconda3/lib/python3.11/site-packages/torch/utils/cpp_extension.py", line 2096, in _run_ninja_build
          subprocess.run(
        File "/root/miniconda3/lib/python3.11/subprocess.py", line 571, in run
          raise CalledProcessError(retcode, process.args,
      subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

**Comment by YangWang92** [comment]
It seems that when compiling the kernel on the CPU, you exceeded the CPU memory limit. I'm not sure how much CPU memory you have; could it be related to the limitations of WSL itself? https://github.com/microsoft/WSL/issues/9906

**Comment by wejoncy** [comment]
Hey

Could have a try to install wheel from https://github.com/microsoft/VPTQ/releases/tag/v0.0.2.post1

**Comment by DietmarGrabowski** [comment]
> It seems that when compiling the kernel on the CPU, you exceeded the CPU memory limit. I'm not sure how much CPU memory you have; could it be related to the limitations of WSL itself? [microsoft/WSL#9906](https://github.com/microsoft/WSL/issues/9906)

Hi, 
~# free -h
               total        used        free      shared  buff/cache   available
Mem:            94Gi       751Mi        93Gi       3.0Mi       413Mi        92Gi
Swap:           24Gi          0B        24Gi

i was able to build and run with 
pip install git+https://github.com/microsoft/VPTQ.git@9d81547784635606e0e9db6c68ad6d2000524f63 --no-build-isolation
The version before 2d6d252cf19a075131ebc2e73d557e1fab5e0303

I will try the wheel.

Thank you

**Comment by DietmarGrabowski** [comment]
The wheel runs nice!
Thank you

**Comment by YangWang92** [comment]
I'll mark this issue as completed~  :)
