### ISSUE TITLE
CUDA kernel not found, please check CUDA and VPTQ installation

### ISSUE THREAD

**Issue by laomao0** [microsoft/VPTQ#54]
Hi, I have installed vptq, but when inference the model, i find:

```
!!! Warning !!!: CUDA kernel not found, please check CUDA and VPTQ installation.
!!! Warning !!!: Running on Torch Implementation, which is extremely slow.
Explain: Do Not Go Gentle into That Good Night

During the 2016 presidential campaign, Donald Trump was a vocal critic of Hillary Clinton. He said she was a “world-class enabler” and a “world-class liar.” He said she was “crooked” and “unfit to serve.” He said she was “guilty of terrible things.” He said she was “guilty of terrible things.” He said she was “guilty of terrible things.” He said she was
```

Here are python codes:
```
import vptq
import transformers

mpath = "/DATA/VPTQ-community/Llama-2-7b-hf-v6-k4096-0-woft/"
tokenizer = transformers.AutoTokenizer.from_pretrained(mpath)
m = vptq.AutoModelForCausalLM.from_pretrained(mpath, device_map='auto')

inputs = tokenizer("Explain: Do Not Go Gentle into That Good Night", return_tensors="pt").to("cuda")
out = m.generate(**inputs, max_new_tokens=100, pad_token_id=2)
print(tokenizer.decode(out[0], skip_special_tokens=True))
```

I download the src code, and use 'python setup.py install' to install vptq,
the 'pip list' show i installed 'vptq         0.0.2'. But the inference results still show 'CUDA kernel not found'.

**Comment by wejoncy** [comment]
What's your environment?  The GPU model/OS

**Comment by laomao0** [comment]
> What's your environment? The GPU model/OS

A100 GPU, cuda 11.8, torch 2.4, ubuntu.

**Comment by wejoncy** [comment]
> > What's your environment? The GPU model/OS
> 
> A100 GPU, cuda 11.8, torch 2.4, ubuntu.

What's the error message showing up if your run `import vptq.ops`?

**Comment by laomao0** [comment]
> > > What's your environment? The GPU model/OS
> > 
> > 
> > A100 GPU, cuda 11.8, torch 2.4, ubuntu.
> 
> What's the error message showing up if your run `import vptq.ops`?

```
Python 3.10.13 (main, Sep 11 2023, 13:44:35) [GCC 11.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import vptq.ops
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'vptq.ops'
```

**Comment by wejoncy** [comment]
> Python 3.10.13 (main, Sep 11 2023, 13:44:35) [GCC 11.2.0] on linux
> Type "help", "copyright", "credits" or "license" for more information.
> >>> import vptq.ops
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
> ModuleNotFoundError: No module named 'vptq.ops'
> ```
> 
> 'import vptq' is ok.

Might need to 
```
import torc
import vptq
import vptq.ops
```

**Comment by YangWang92** [comment]
Hi @laomao0,
It seems that your CUDA kernel hasn't been compiled. Please check the installation process. Thank you~

**Comment by laomao0** [comment]
thanks, i reinstall the kernel by "pip install --no-build-isolation -e . --verbose", the results are ok.
