### ISSUE TITLE
How can I use VPTQ to quantize my own models?

### ISSUE THREAD

**Issue by IEI-mjx** [microsoft/VPTQ#56]
As far as I could see, the quantization methods was not provided in this project. 
All examples showed here were how to inference with vptq models, rather than the quantization tutorials.
Or I might have misunderstood this project, maybe you can show me an example about how to quantize models with vptq?

**Comment by YangWang92** [comment]
Yes, haha, you've anticipated what I am planning to do next. It's definitely possible. I've analyzed the structure of Llama 3.2, and at the very least, we can quantize the decoder part (which is the part with the most parameters). If you're interested, I'd welcome any collaboration!

**Comment by YangWang92** [comment]
Please hold on, I will release the quantized model in the next 1-2 weeks, and you are welcome to test it.

**Comment by gtkacz** [comment]
@YangWang92 will this work with BERT models too?

**Comment by ponponon** [comment]
> Please hold on, I will release the quantization algorithm in the next 1-2 weeks, and you are welcome to test it.请稍等，我将在未来1-2周内发布量化算法，欢迎您测试。

Instruct- Is GPTQ similar to VPTQ in qwen/Qwen2-VL-7B-Instruct- GPTQ-INT4? Is this all about model quantification?

Does VPTQ have any unique advantages over GPTQ?

**Comment by ponponon** [comment]
> Please hold on, I will release the quantization algorithm in the next 1-2 weeks, and you are welcome to test it.请稍等，我将在未来1-2周内发布量化算法，欢迎您测试。

Can it be used to quantize ZhipuAI/glm-4v-9b?

https://huggingface.co/THUDM/glm-4v-9b

https://modelscope.cn/models/ZhipuAI/glm-4v-9b

**Comment by YangWang92** [comment]
> [@YangWang92](https://github.com/YangWang92) will this work with BERT models too?

I have not verified whether VPTQ works on encoder models, but from my intuition, quantizing the encoder should be easier. For example, methods similar to GPTQ perform reasonably well on BERT. I will test this while quantizing VLMs‘ encoder as well.

**Comment by YangWang92** [comment]
> > Please hold on, I will release the quantization algorithm in the next 1-2 weeks, and you are welcome to test it.请稍等，我将在未来1-2周内发布量化算法，欢迎您测试。
> 
> Instruct- Is GPTQ similar to VPTQ in qwen/Qwen2-VL-7B-Instruct- GPTQ-INT4? Is this all about model quantification?
> 
> Does VPTQ have any unique advantages over GPTQ?

VPTQ will achieve better accuracy at <3 bits, and you can check our early results in the tech report. https://github.com/microsoft/VPTQ/blob/main/VPTQ_tech_report.pdf ![Image](https://github.com/user-attachments/assets/b8bb4362-3a32-48d3-b10f-10b83fb6a73f)

**Comment by YangWang92** [comment]
> > Please hold on, I will release the quantization algorithm in the next 1-2 weeks, and you are welcome to test it.请稍等，我将在未来1-2周内发布量化算法，欢迎您测试。
> 
> Can it be used to quantize ZhipuAI/glm-4v-9b?
> 
> https://huggingface.co/THUDM/glm-4v-9b
> 
> https://modelscope.cn/models/ZhipuAI/glm-4v-9b

I will still working on VLMs and please wait a few weeks.

**Comment by YangWang92** [comment]
Hi @ponponon @gtkacz @IEI-mjx @mtodd,

The VPTQ algorithm has been early-released at the [algorithm branch](https://github.com/microsoft/VPTQ/tree/algorithm), and you can check out the [tutorial](https://github.com/microsoft/VPTQ/blob/algorithm/algorithm.md). The current release is still in its early stages. This code is an early-release version extracted from a complete experimental codebase. Some details still need to be fully revised, so please use and test it cautiously.

Thanks!

**Comment by bhavyajoshi-mahindra** [comment]
Any plans to support Qwen2-VL model?

**Comment by YangWang92** [comment]
> Any plans to support Qwen2-VL model?

Please be patient, I am still developing it, and it might take 1-2 months.

**Comment by caronzh03** [comment]
> The VPTQ algorithm has been early-released at the [algorithm branch](https://github.com/microsoft/VPTQ/tree/algorithm), and you can check out the [tutorial](https://github.com/microsoft/VPTQ/blob/algorithm/algorithm.md). 

Hi, is there any guide / recipe on how to compute the Hessian matrices for a custom model?

**Comment by YangWang92** [comment]
Hi @caronzh03, 

We are currently using the Hessian matrix collection from https://github.com/Cornell-RelaxML/quip-sharp?tab=readme-ov-file#quantization. Please refer to this link for more details. 

Additionally, I am modifying the code for collecting the Hessian matrix and will make it public in the future.

Thanks!

**Comment by gtkacz** [comment]
@YangWang92

> I have not verified whether VPTQ works on encoder models, but from my intuition, quantizing the encoder should be easier. For example, methods similar to GPTQ perform reasonably well on BERT. I will test this while quantizing VLMs‘ encoder as well.

Did you ever get around to testing this? Really interest to use this on a BERT encoder

**Comment by YangWang92** [comment]
I expect to try the BERT model in about 2-3 weeks, but this is not my main task at the moment. Do you have any recommended settings?

**Comment by caronzh03** [comment]
> Hi [@caronzh03](https://github.com/caronzh03),
> 
> We are currently using the Hessian matrix collection from https://github.com/Cornell-RelaxML/quip-sharp?tab=readme-ov-file#quantization. Please refer to this link for more details.
> 
> Additionally, I am modifying the code for collecting the Hessian matrix and will make it public in the future.
> 
> Thanks!

Hi @YangWang92 , did you get a chance to publish the Hessian matrix collection code?

**Comment by YangWang92** [comment]
> > Hi [@caronzh03](https://github.com/caronzh03),
> > We are currently using the Hessian matrix collection from https://github.com/Cornell-RelaxML/quip-sharp?tab=readme-ov-file#quantization. Please refer to this link for more details.
> > Additionally, I am modifying the code for collecting the Hessian matrix and will make it public in the future.
> > Thanks!
> 
> Hi [@YangWang92](https://github.com/YangWang92) , did you get a chance to publish the Hessian matrix collection code?

Hi @caronzh03, 

You can check out the code here:  
- [https://github.com/VPTQ/hessian_collector/tree/master](https://github.com/VPTQ/hessian_collector/tree/master)  
- [https://github.com/YangWang92/quip-sharp/tree/wy/hessian](https://github.com/YangWang92/quip-sharp/tree/wy/hessian)  

I am still in the process of refactoring and decoupling the Hessian collection code from **quip-sharp**.  

For **decode-only LLMs**, you can use [[this script](https://github.com/VPTQ/hessian_collector/blob/master/hessian_collector.py)](https://github.com/VPTQ/hessian_collector/blob/master/hessian_collector.py) to obtain the model's Hessian.  

For more complex **VLMs** (which typically involve more intricate cross-attention dependencies), I have temporarily provided an implementation based on the `accelerator` library:  
[https://github.com/VPTQ/hessian_collector/blob/master/vlm_hessian_collector.py](https://github.com/VPTQ/hessian_collector/blob/master/vlm_hessian_collector.py).  

This implementation is quite rudimentary – it loads all layers of the model into GPU memory and uses forward hooks to collect the Hessian. Typically, you will need a machine with **4 or 8 GPUs** to load both the model and the hooks.

We will release a series of multimodal models in the coming 4-6 weeks. Stay tuned!

**Comment by caronzh03** [comment]
hi @YangWang92 , if I have a fine-tuned Qwen-7B model, is the quantization quality better if I use my fine-tuning dataset samples to collect Hessian? Or using the default `togethercomputer/RedPajama-Data-1T-Sample` from your `hessian_collector.py` code is as good?

**Comment by YangWang92** [comment]
Hi @caronzh03 , I think it will be helpful to use your calibration datasets. The current calibration dataset is Redpajama-sample-1T, which includes all knowledge areas. My colleague @wejoncy designed an end-to-end quantization toolchain that supports VPTQ and hessian collection; maybe you can use this tool to evaluate your idea quickly. https://github.com/wejoncy/QLLM

**Comment by xiangf856** [comment]
Hello, I would like to ask whether the code for compressing a large model using the VPTQ algorithm is open-sourced. I can only find the code for how to use models that have already been quantized with VPTQ.

**Comment by YangWang92** [comment]
> Hello, I would like to ask whether the code for compressing a large model using the VPTQ algorithm is open-sourced. I can only find the code for how to use models that have already been quantized with VPTQ.

https://github.com/microsoft/vptq?tab=readme-ov-file#vptq-algorithm-early-released
