### ISSUE TITLE
Possibility of quantising multimodal models like Qwen-VL and llama 3.2 Vision?

### ISSUE THREAD

**Issue by yueqianh** [microsoft/VPTQ#57]
Thanks to the development team for the wonderful work so far!

As we are still waiting for the quantisation algorithm to be published, I am just wondering about the possibility of quantising multimodal models like Qwen-VL and llama 3.2 Vision in the future. May I know if this is possible based on how VPTQ works?

**Comment by YangWang92** [comment]
Yes, haha, you've anticipated what I am planning to do next. It's definitely possible. I've analyzed the structure of Llama 3.2, and at the very least, we can quantize the decoder part (which is the part with the most parameters). If you're interested, I'd welcome any collaboration!

**Comment by YangWang92** [comment]
Please hold on, I will release the quantized model in the next 1-2 weeks, and you are welcome to test it. The code I've implemented is a bit messy at the moment, as I am still separating parts that are currently irrelevant.

**Comment by yueqianh** [comment]
That is great news! Thank you for the quick response.

**Comment by YangWang92** [comment]
Hi @yueqianh,
The VPTQ algorithm has been early-released at the [algorithm branch](https://github.com/microsoft/VPTQ/tree/algorithm), and you can check out the [tutorial](https://github.com/microsoft/VPTQ/blob/algorithm/algorithm.md). The current release is still in its early stages. This code is an early-release version extracted from a complete experimental codebase. Some details still need to be fully revised, so please use and test it cautiously.

Thanks!
