### ISSUE TITLE
may be some issuses about llama-2-7b model.

### ISSUE THREAD

**Issue by laomao0** [microsoft/VPTQ#62]
Hi, I down load llama2-7b model from 'https://huggingface.co/collections/VPTQ-community/reproduced-vptq-tech-report-baseline-66fbf1dffe741cc9e93ecf04', then I test the ppl of wikitext2 using seqlen 2048, i get the following results:

Llama-2-7b-hf-v6-k4096-0-woft 	         7.136
Llama-2-7b-hf-v6-k4096-0-ft	                6.5705
Llama-2-7b-hf-v4-k4096-0-woft 	        5.8186
Llama-2-7b-hf-v6-k4096-4096-woft 	7.136

the ppl of [Llama-2-7b-hf-v6-k4096-4096-woft] is the same with [Llama-2-7b-hf-v6-k4096-0-woft],
and i see model.safetensors of [Llama-2-7b-hf-v6-k4096-4096-woft] is 2.16GB, which is the same as [Llama-2-7b-hf-v6-k4096-0-woft].

Following readme [Quick Estimation of Model Bitwidth (Excluding Codebook Overhead) 
https://github.com/microsoft/VPTQ/blob/main/README.md]

v6-k4096-4096 --> avg bit = 12/6 + 12/6 = 4bit
model size est = 7B*4/8=3.5GB, which is not 2.16GB.

**Comment by OpenSourceRonin** [comment]
Thank you for pointing this out. It seems I have named the model incorrectly. The correct model name should be Llama-2-7b-hf-v6-k4096-0-woft https://huggingface.co/VPTQ-community/Llama-2-7b-hf-v6-k4096-4096-woft/blob/main/config.json#L36, but with name Llama-2-7b-hf-v6-k4096-4096-woft, and Llama-2-7b-hf-v6-k4096-4096-woft is missed. Let me fix this by updating models. Thanks!

**Comment by laomao0** [comment]
> Thank you for pointing this out. It seems I have named the model incorrectly. The correct model name should be Llama-2-7b-hf-v6-k4096-0-woft https://huggingface.co/VPTQ-community/Llama-2-7b-hf-v6-k4096-4096-woft/blob/main/config.json#L36, rather than Llama-2-7b-hf-v6-k4096-4096-woft, and Llama-2-7b-hf-v6-k4096-4096-woft is missed. Let me fix this by updating models. Thanks!

OK

**Comment by OpenSourceRonin** [comment]
I have updated the model https://huggingface.co/VPTQ-community/Llama-2-7b-hf-v6-k4096-4096, and please help me to check the result.

**Comment by laomao0** [comment]
> I have updated the model https://huggingface.co/VPTQ-community/Llama-2-7b-hf-v6-k4096-4096, and please help me to check the result.
 
                                                                      wiki       |  c4
 Llama-2-7b-hf-v6-k4096-4096 [4.03bit]   | 5.21374   | 6.7469 

The 4096-ctx ppl looks similar to the paper.

**Comment by OpenSourceRonin** [comment]
Thanks for your confirmation!
