### ISSUE TITLE
Is it possible to run VPTQ in CPU only?

### ISSUE THREAD

**Issue by yueqianh** [microsoft/VPTQ#67]
Given the small size of the quantised models, I am wondering if it is possible to run VPTQ in CPU only?

Currently, this does not seem to be possible as one of the functions require CUDA.

**Comment by YangWang92** [comment]
The current stage of VPTQ can technically run on a CPU. You can disable the support for vptq.ops on CUDA and ROCM, which will make it natively run on PyTorch's CPU backend.  (only use self.dequant(), for example)

https://github.com/microsoft/VPTQ/blob/main/vptq/layers/vqlinear.py#L649-L651
```python
# qweight = self.fast_dequant()
#             if qweight is None:
    qweight = self.dequant()
```

However, it is highly discouraged to do so because the FLOPS of CPUs are still relatively low, and there is a lack of adequate optimizations at this stage.

**Comment by YangWang92** [comment]
Recently, some colleagues asked if it is possible to use the latest CPUs (which usually have very large LLCs). I think this could be a very feasible system optimization. I'll close this issue for now, and I will seriously consider this. Welcome to contribue to CPU support if you like. Thank! Yang

**Comment by zianttt** [comment]
I’ve been trying to run VPTQ in CPU-only mode following the instructions provided. However, I encountered an issue where the ```fast_gemv``` function appears to require CUDA as well, preventing the model from functioning on a CPU-only setup. Could you kindly advise on any possible solutions or workarounds to run VPTQ without CUDA? Thanks in advance!

**Comment by YangWang92** [comment]
> I’ve been trying to run VPTQ in CPU-only mode following the instructions provided. However, I encountered an issue where the `fast_gemv` function appears to require CUDA as well, preventing the model from functioning on a CPU-only setup. Could you kindly advise on any possible solutions or workarounds to run VPTQ without CUDA? Thanks in advance!

Hi @zianttt, 
I'm very sorry, I missed your message and only just saw it. I will follow up with the CPU method soon. Please wait a moment as I need to implement a CPU version of the dequant function.

Thanks!
Yang

**Comment by zianttt** [comment]
Hi Yang,

No worries, thank you so much for your reply! Looking forward for the CPU
support.

Once again thank you for your work in developing this!

Regards,
Tan Zi An

**Comment by akostadinov** [comment]
No updates?
