### ISSUE TITLE
Multiple GPU Support

### ISSUE THREAD

**Issue by twoxfh** [microsoft/VPTQ#73]
Problem: When setting the CUDA_VISIBLE_DEVICES variable to the available GPU's the python script only see's one GPU. The following test of a 40gb model fails after the first GPU is exhausted. 

Test: CUDA_VISIBLE_DEVICES=0,1 python -m vptq --model=../Mistral-Large-Instruct-2407-v8-k65536-256-woft --prompt="Explain: Do Not Go Gentle into That Good Night" 

Multiple GPU support would be helpful to test larger quants. Thanks for reading and considering.

**Comment by YangWang92** [comment]
Hi, welcome to follow our project. I've just modified the settings of the accelerator device map, and now it should default to using multiple GPUs to load the model as much as possible. Please note that our current multi-card inference is only a naive implementation, dependent on the accelerator, and only utilizes multiple cards to load the model into GPU memory. It does not accelerate the inference speed of the model. We will continue to focus on optimizing the speed of inference in future developments. Please stay tuned for our updates. Thank you.  https://github.com/microsoft/VPTQ/pull/74

**Comment by twoxfh** [comment]
@YangWang92  Using your branch my two 3090's now work with a 40gb model. Thanks for your quick response and the teams work toward brining a new quant technology. 

python -m vptq --model=../../Qwen2.5-72B-Instruct-v8-k65536-65536-woft --prompt="Explain: Do Not Go Gentle into That Good Night"

**Comment by YangWang92** [comment]
Thank you for your confirmation! Please feel free to offer any suggestions. We are continuously working to expand our research, and I would appreciate it if you could help promote our VPTQ when you have the time. :)
