### ISSUE TITLE
New Quantized Model Request

### ISSUE THREAD

**Issue by JoesSattes** [microsoft/VPTQ#78]
Thank you for your valuable contributions to the community; your work looks great! I came across this 70B model: Llama-3.1-Nemotron-70B-Instruct, and its benchmark results are impressive. Could you please provide the quantized weights for this model?

**Comment by OpenSourceRonin** [comment]
Hahaha, I'm just running the quantization of this model. I will release this model in the next two days.

**Comment by JoesSattes** [comment]
That’s fantastic news! Thank you for the update.

**Comment by OpenSourceRonin** [comment]
![Image](https://github.com/user-attachments/assets/50c0338e-160b-4ff0-924f-7f43c0792fda)
Hi all,

The new VPTQ Llama 3.1 Nemotron 70B Instruct HF without finetune is now available for download at https://github.com/microsoft/VPTQ?tab=readme-ov-file#evaluation and https://huggingface.co/collections/VPTQ-community/vptq-llama-31-nemotron-70b-instruct-hf-without-finetune-671730b96f16208d0b3fe942. 

You are welcome to try it out!
We are continuing to work on quantizing the 4-6 bit versions. Please stay tuned!
