### ISSUE TITLE
Slow Inference on A2 with VPTQ Compared to Ollama

### ISSUE THREAD

**Issue by WpythonW** [microsoft/VPTQ#86]
I'm encountering performance issues with VPTQ on an Nvidia A2 GPU. Here's a comparison of my results:
Model: Qwen 2.5

VPTQ Performance (Tokens/sec):
v8-k256-256-woft: 5.22
v8-k65536-256-woft: 5.21
v8-k65536-65536-woft: 2.10
v16-k65536-65536-woft: 2.02
v8-k65536-0-woft: 3.77

Ollama Results (Tokens/sec)::
q6 K: 10.06
q5 0: 14.30

What am I doing wrong, and why is VPTQ inference significantly slower on the same hardware?

Thank you!

**Comment by YangWang92** [comment]
Thanks for letting me know. I’ve encountered a similar issue, and I’m still investigating the cause. For now, you can try reverting to commit 83ab80a46b94fb8cd5cbb7200eed8ff282c065bb to see if it helps, or directly use the previous `model_base` from [this link](https://github.com/microsoft/VPTQ/pull/74/files). 

Additionally, we currently haven’t optimized for inference yet. As you can see, our inference implementation is purely based on PyTorch with simple CUDA kernels. In the future, we plan to leverage existing frameworks like vllm or llama.cpp, which will greatly improve our inference performance. Apologies for the inconvenience.

**Comment by YangWang92** [comment]
In the next 1-2 months, I will continue optimizing the inference. Please stay tuned.

**Comment by YangWang92** [comment]
I'm trying to discuss with ggerganov at [this link](https://github.com/ggerganov/llama.cpp/discussions/9974#discussioncomment-11027488), can you help support us? (upvote) :) We really want to integrate into llama.cpp/ollama.

**Comment by YangWang92** [comment]
BTW, I found this repo https://github.com/WpythonW/VTPQ-comparsion-custom_UI-example.

Thank you so much for paying attention to our project! 

I have a simple web UI here: https://github.com/microsoft/VPTQ/blob/main/vptq/app.py, though it's still quite basic. 

The community has contributed with the visualization of GPU memory usage and utilization, thanks to them!
 ![Image](https://github.com/user-attachments/assets/80ddc072-c444-416a-b272-c3b53dea9a8b)
